### ISSUE TITLE
update ETS model to predict rcc90

### ISSUE THREAD

**Issue by dlebauer** [genophenoenvo/neon-datasets#60]
The first phenology model predicts greeness (gcc90) https://github.com/genophenoenvo/neon-datasets/blob/7b89995c7c63dc5d4fe4146041e75be50f6df3bd/models/simple/ets_forecast.R#L40 

Can this be updated to predict rcc90 either as a single multivariate model or a new univariate model?

References: https://github.com/genophenoenvo/neon-datasets/tree/main/models#simple-team-peg and https://otexts.com/fpp3

Ask Chris about cron job originally discussed in this thread https://cyverse.slack.com/archives/CQAATRMCM/p1616445617007400

**Comment by jessicaguo** [comment]
[PR 66](https://github.com/genophenoenvo/neon-datasets/pull/66) adds a separate model for rcc, and combines the output for submission to the fall challenge. I could not get the EML libraries to load, so that portion of code is untested. Will check https://data.ecoforecast.org/minio/forecasts/phenology/ to see if today's version will upload successfully.

**Comment by dlebauer** [comment]
PR merged - thanks!

lets check to make sure rcc_90 is being predicted before closing (09-10 and 09-12 didn't have rcc_90)
